import type { Citation, Report } from './types'

const penaltyCitation: Citation = {
  id: 'cp-act-2-46-ii',
  title: 'Consumer Protection Act, 2019',
  section: 'Section 2(46)(ii)',
  description: 'Lists wholly disproportionate consumer penalties as one feature of an unfair contract.',
  relevance: 'This may be relevant to the cancellation charge quoted in the contract. Whether it applies depends on the full agreement and facts.',
  url: 'https://www.indiacode.nic.in/bitstream/123456789/16939/1/a2019-35.pdf',
}

const chargeCitation: Citation = {
  id: 'cp-act-2-46-vi',
  title: 'Consumer Protection Act, 2019',
  section: 'Section 2(46)(vi)',
  description: 'Includes an unreasonable charge, obligation, or condition that disadvantages a consumer in the definition of an unfair contract.',
  relevance: 'This is a possible legal framework for reviewing the added service charge; the tool does not decide whether the charge is unlawful.',
  url: 'https://www.indiacode.nic.in/bitstream/123456789/16939/1/a2019-35.pdf',
}

export const demoReport: Report = {
  report_id: 'demo-contract-001',
  document_name: 'Sample subscription terms.pdf',
  jurisdiction: 'India · Central',
  language: 'English',
  analysis_mode: 'demo',
  contract_summary: 'A fictional online subscription contract with an automatic renewal, an extra service charge, a restrictive cancellation fee, a right to change terms, and limits on liability.',
  contract_summary_hi: 'यह एक काल्पनिक ऑनलाइन सब्सक्रिप्शन समझौता है। इसमें अपने आप नवीनीकरण, अतिरिक्त सेवा शुल्क, रद्द करने पर शुल्क, शर्तें बदलने का अधिकार और ज़िम्मेदारी की सीमाएँ शामिल हैं।',
  findings: [
    {
      id: 'demo-renewal',
      category: 'Renewal & cancellation',
      title: 'Subscription renews automatically',
      risk: 'Review',
      confidence: 0.98,
      page: 1,
      original_clause: 'Your plan will renew automatically for successive one-year periods unless you cancel at least 30 days before the renewal date.',
      plain_language: 'The subscription rolls over for another year unless you cancel at least 30 days before it renews.',
      plain_language_hi: 'सब्सक्रिप्शन हर साल अपने आप एक और वर्ष के लिए बढ़ जाएगा, जब तक आप नवीनीकरण से कम-से-कम 30 दिन पहले रद्द न करें।',
      why_it_matters: 'Missing the cancellation window could commit you to another year of payments.',
      why_it_matters_hi: 'रद्द करने की समय-सीमा छूटने पर आपको एक और वर्ष तक भुगतान करना पड़ सकता है।',
      suggested_action: 'Check the renewal date and set a reminder well before the 30-day deadline.',
      citations: [],
    },
    {
      id: 'demo-extra-fee',
      category: 'Additional charges',
      title: 'A separate service charge may be added',
      risk: 'Review',
      confidence: 0.94,
      page: 2,
      original_clause: 'A platform service charge of up to 8% may be added to each renewal invoice. The charge may change from time to time.',
      plain_language: 'The final renewal bill may include an extra charge of up to 8%, and that amount may change.',
      plain_language_hi: 'नवीनीकरण के बिल में 8% तक अतिरिक्त शुल्क जुड़ सकता है और यह राशि समय के साथ बदल सकती है।',
      why_it_matters: 'The total cost may be higher than the advertised subscription price.',
      why_it_matters_hi: 'कुल लागत विज्ञापित सब्सक्रिप्शन कीमत से अधिक हो सकती है।',
      suggested_action: 'Ask for the current total price and how much notice you will get before the fee changes.',
      citations: [chargeCitation],
    },
    {
      id: 'demo-cancellation-fee',
      category: 'Refunds & termination',
      title: 'Early cancellation may carry a large charge',
      risk: 'Review',
      confidence: 0.96,
      page: 3,
      original_clause: 'If you terminate before the end of your annual term, an early termination charge equal to 90% of the remaining subscription price will apply. Amounts already paid are non-refundable.',
      plain_language: 'Leaving early could cost 90% of the remaining yearly price, and the contract says you cannot get back amounts already paid.',
      plain_language_hi: 'साल पूरा होने से पहले छोड़ने पर बची हुई सालाना कीमत का 90% शुल्क लग सकता है। पहले से चुकाई गई राशि वापस न मिलने की बात भी लिखी है।',
      why_it_matters: 'This could make it expensive to stop using the service. The size and effect of the fee need context and professional review.',
      why_it_matters_hi: 'इससे सेवा बंद करना महँगा हो सकता है। शुल्क कितना उचित है, यह समझने के लिए संदर्भ और विशेषज्ञ समीक्षा ज़रूरी है।',
      suggested_action: 'Ask the provider to explain how the amount is calculated and whether any cancellation or refund exceptions apply.',
      citations: [penaltyCitation],
    },
    {
      id: 'demo-unilateral-change',
      category: 'Changes to terms',
      title: 'The provider can change terms by notice',
      risk: 'Moderate',
      confidence: 0.91,
      page: 3,
      original_clause: 'We may revise these terms at any time by posting an updated version on our website. Continued use after posting means you accept the revised terms.',
      plain_language: 'The provider says it can change the agreement by posting new terms. Continuing to use the service is treated as acceptance.',
      plain_language_hi: 'प्रदाता कहता है कि वह वेबसाइट पर नई शर्तें डालकर समझौता बदल सकता है। सेवा का उपयोग जारी रखना स्वीकृति माना जाएगा।',
      why_it_matters: 'The change process may not give you a direct notice or a clear chance to cancel before new terms take effect.',
      why_it_matters_hi: 'बदलाव की सूचना सीधे न मिले या नई शर्तें लागू होने से पहले रद्द करने का स्पष्ट विकल्प न हो सकता है।',
      suggested_action: 'Check how notice is delivered, when changes take effect, and whether you can cancel without a fee.',
      citations: [],
    },
    {
      id: 'demo-dispute',
      category: 'Disputes',
      title: 'Disputes go to arbitration in one city',
      risk: 'Informational',
      confidence: 0.89,
      page: 4,
      original_clause: 'Any dispute will be resolved by a sole arbitrator seated in Bengaluru. The proceedings will be conducted in English.',
      plain_language: 'The contract sends disputes to one arbitrator in Bengaluru, with proceedings in English.',
      plain_language_hi: 'समझौते के अनुसार विवाद का निर्णय बेंगलुरु में एक मध्यस्थ करेगा और कार्यवाही अंग्रेज़ी में होगी।',
      why_it_matters: 'The location, language, and process can affect how practical it is to raise a dispute.',
      why_it_matters_hi: 'स्थान, भाषा और प्रक्रिया से विवाद उठाना कितना व्यावहारिक होगा, यह प्रभावित हो सकता है।',
      suggested_action: 'Keep this clause available and ask a lawyer how it interacts with your consumer remedies.',
      citations: [],
    },
    {
      id: 'demo-liability',
      category: 'Liability',
      title: 'The provider limits its liability',
      risk: 'Review',
      confidence: 0.93,
      page: 4,
      original_clause: 'To the maximum extent permitted by law, our total liability will not exceed the fees paid by you in the three months before the event giving rise to the claim.',
      plain_language: 'The provider says its responsibility for claims is capped at three months of fees.',
      plain_language_hi: 'प्रदाता कहता है कि दावे के लिए उसकी अधिकतम ज़िम्मेदारी पिछले तीन महीनों की फीस तक सीमित होगी।',
      why_it_matters: 'A cap could limit the amount the contract says you may recover. Its effect depends on the type of claim and applicable law.',
      why_it_matters_hi: 'यह सीमा बताई गई वसूली की राशि को सीमित कर सकती है। असर दावे के प्रकार और लागू कानून पर निर्भर करता है।',
      suggested_action: 'Check which claims the cap applies to and whether any important exceptions are listed elsewhere.',
      citations: [],
    },
  ],
  citations: [chargeCitation, penaltyCitation],
}
